nmos/NOTICE
nmos/README.md
nmos/docker/NOTICE
nmos/docker/UserConfig.py
nmos/docker/docker-compose.yaml
nmos/docker/node.json
nmos/docker/registry.json
nmos/docker/run.sh
nmos/k8s/bcs/nmos-client.yaml
nmos/k8s/testing/nmos-registry.yaml
nmos/k8s/testing/nmos-testing.yaml
nmos/patches/build-nmos-cpp.patch
nmos/patches/nmos-cpp.patch

Enable nmos client for bcs 
* Enable nmos client for bcs
* Enable nmos registry for bcs
* Enable testing tool for bcs
* Enable k8s for nmos
* Enable docker for nmos
* Run script
* Add readme
* Add information about license

Add nmos support

---

.gitmodules

Fix submodules for nmos

---

.github/workflows/build_tiber.yml
.github/workflows/dependency-review.yaml
.github/workflows/linters.yml
.github/workflows/scorecard.yml
Dockerfile
build.sh
gRPC/compile.sh

ADDED: Integrate ffmpeg application launcher service in Docker
Note: This PR is based on original PR made earlier by Walid, named "Integrate ffmpeg application launcher service in Docker."
Signed-off-by: Aly, Walid <walid.aly@intel.com> [walidbarakat](https://github.com/OpenVisualCloud/Intel-Tiber-Broadcast-Suite/commits?author=walidbarakat)
FEATURE ADDED: Full Docker caching service implementation was added and all current dockerd problems seems to be resolved.
ADDED: Final docker daemon fixes for caching system
FIX: Updated and finally fixed the build_tiber.yml and resolve the issues regarding build system.
FIX: Minor adjustments have been made to other yaml files/PR build system.
FIX: Minor adjustments made to Dockerfile for caching purposes.
ADDED: Full caching system implemented and …

Integrate ffmpeg application launcher service in Docker

---

gRPC/README.md

Add command passing instructions for FFmpeg gRPC service.

Add command passing instruction

---

launcher/go.mod
launcher/go.sum

Fix CVE related to 3rd party package that was required in golang bcs launcher

Fix vulnerability alerts

---

gRPC/k8s/manifests.yaml

Added deployment and service for ffmpeg pipeline that listens to requests from nmos client

Add deployment for ffmpeg pipeline

---

gRPC/cmd_pass_client.cc
nmos/docker/node.json
nmos/docker/run.sh
nmos/k8s/bcs/nmos-client.yaml
nmos/patches/build-nmos-cpp.patch
nmos/patches/nmos-cpp.patch

It requires to copy grpc dir under nmos/nmos-cpp/Development for ffmpeg communication

Add nmos and grpc communication for ffmpeg

---

docs/attribution.md

add license for BCS

---

gRPC/CMakeLists.txt
gRPC/CmdPassImpl.cc
gRPC/FFmpeg_wrapper_client.cc
gRPC/FFmpeg_wrapper_client.h
gRPC/config_params.hpp
gRPC/config_serialize_deserialize.hpp
gRPC/ffmpeg_pipeline_generator.cpp
gRPC/ffmpeg_pipeline_generator.hpp
gRPC/unit_test/CMakeLists.txt

Add BCS application launcher Config and generate FFmpeg pipelines based on it

BCS application launcher Config

---

.github/workflows/coverity_build.yml
.github/workflows/coverity_reports.yml

Update openssf permissions fix

Update openssf permissions fix

---

.github/workflows/scorecard.yml
docs/README.md

Fix: OpenSSF Scorecard.yml errors
Refactor: Naming convention changed to more descriptive

Fix: OpenSSF Scorecard.yml errors

---

.github/workflows/trivy.yml

FIX:
* move trivy scan to separate pipeline

separate build workflow from trivy workflow

---

src/nmos/nmos-node/node_implementation.cpp

-changes ip address parsing in handler when there is IS-05 connection
This commit [Fix parsing in nmos](https://github.com/OpenVisualCloud/Intel-Tiber-Broadcast-Suite/commit/77087f379cf5311f878c7178335fc7e069b9ee02) depends on https://github.com/OpenVisualCloud/Intel-Tiber-Broadcast-Suite/pull/66

Fix nmos parsing

---

src/nmos/nmos-node/CMakeLists.txt
src/nmos/nmos-node/intel_config_parser.cpp
src/nmos/nmos-node/intel_config_parser.h
src/nmos/nmos-node/main.cpp
src/nmos/nmos-node/unit_tests/CMakeLists.txt
src/nmos/nmos-node/unit_tests/config_parser_tests.cc

Add bcs-nmos-node unit test framework with some basics tests, 
This PR is based on #66 , until #66 is not merged, this PR stays as draft

Add bcs-nmos-node UT

---

.github/workflows/build_binaries.yml

ADD: 
* gRPC unit tests
* nmos unit tests

add nmos and gRPC unit test

---

build.sh

FIX: Process of docker build in build.sh
- added missing proxy settings.

FIX: Process of docker build in build.sh

---

.github/workflows/coverity_build.yml
tests/intel-node-multiviewer-h264.json
tests/intel-node-rx-h264.json
tests/intel-node-tx-h264.json
tests/test_docker_nmos_multiviewer.sh
tests/test_docker_nmos_rx.sh
tests/test_docker_nmos_tx.sh

Added the ability to select config depending on pixel format. Added h264 configuration files.

BCS tests improvement - configuration files

---

.github/workflows/base_build.yml
.github/workflows/coverity_build.yml
.github/workflows/dependency-review.yaml
.github/workflows/docker_build.yml
.github/workflows/linters.yml
.github/workflows/trivy.yml

update workflows names

---

launcher/go.mod
launcher/go.sum
src/nmos/k8s/testing-dev/nmos-testing.yaml

1. Update vulnerable GO component oauth2 from 0.24 to 0.27
2.  Fix kubernetes Vulnerability KSV014

Address high security issues

---

launcher/README.md
launcher/cmd/main.go
launcher/configuration_files/bcs-launcher.yaml
launcher/configuration_files/bcslauncher-k8s-config.yaml
launcher/configuration_files/bcslauncher-static-config-custom-net-rx.yaml
launcher/configuration_files/bcslauncher-static-config-custom-net-tx.yaml
launcher/configuration_files/bcslauncher-static-config-host-net-rx.yaml
launcher/configuration_files/bcslauncher-static-config-host-net-tx.yaml
launcher/internal/container_controller/container_controller.go
launcher/resources_library/utils/operations.go
launcher/resources_library/utils/parser.go
launcher/resources_library/utils/parser_test.go
launcher/resources_library/workloads/workloads.go

- fixed network mode host vs custom network
- changed key from sourcePort to nmosPort in config
- added sample configs with description
- changed way of passed argument in script
- fix command in ffmpeg pipeline in container run from launcher level

fix network issue in docker mode of launcher

---

src/app/ffmpeg_pipeline_generator.cc

Fix recorder pipeline generation,
Fix upscale pipeline generation.

Fix recorder pipeline generation

---

examples/intel-node-rx-h265-2-streams.json
examples/intel-node-tx-h265-2-streams.json
src/app/ffmpeg_pipeline_generator.cc
src/common/config_params.hpp
src/gRPC/config_serialize_deserialize.hpp
src/gRPC/unit_test/ffmpeg_pipeline_generator_test.cc
src/nmos/nmos-node/intel_config_parser.cpp
src/nmos/nmos-node/node_implementation.cpp
src/nmos/nmos-node/unit_tests/config_parser_tests.cc
tests/intel-node-rx-h264.json
tests/intel-node-rx-h265.json

Add optional preset and profile fields to Video struct and update pipeline generation

Add optional preset and profile fields to Video struct and update pipeline generation

---

.github/configs/.shellcheckrc
.github/workflows/docker_build.yml
.shellcheckrc
build.sh
scripts/common.sh
versions.env

FIX: Add caching and push for containers.
FIX: Docker tag for pull request
FIX: Docker buildx build permissions for packages and no push.
ADDED: .shellcheckrc in main directory for VS Studio compliance. 
FIX: Minor fixes in code.
FIX: Major script `common.sh` update and fixtures.
WARNING: Include breaking changes in script itself but fixes most of the issues it introduced.

FIX: Add caching and push for containers.

---

tests/nmos-is05-controller/README.md
tests/nmos-is05-controller/threaded-nmos-controller05.py

Added support for test script to connect more than one sender/receiver
No need to edit json config files anymore :)

Add selection to python nmos controller
